[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
force = true # ensure that we always redirect
from = "/"
headers = {X-From = "Netlify"}
signed = "API_SIGNATURE_TOKEN"
to = "https://grammy.dev"
