name: Lint Commit Messages

on:
    - pull_request
    - push

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check commit message
              uses: wagoid/commitlint-github-action@v4
